CREATE VIEW [dbo].[VW_OFI_VACACIONES_OPTIMIZADO] AS
SELECT TE.CO_EMPR, E.DE_NOMB_CORT AS NO_EMPR, TE.CO_SEDE, V.CO_TRAB, RTRIM(TP.NO_APEL_PATE) + ' ' + RTRIM(TP.NO_APEL_MATE) + ' ' + RTRIM(TP.NO_TRAB) AS APELLIDOS_NOMBRES, SUBSTRING(V.PE_VACA, 1, 4) + '-' + SUBSTRING(V.PE_VACA, 5, 8) AS PERIODO_VACACIONAL, AY.DE_OBJE_TIPO AS TIPO, V.FE_INIC_VACA AS FECHA_INICIAL, V.FE_FINA_VACA AS FECHA_FINAL, CONVERT(INT, V.NU_DIAS) AS NRO_DIAS
FROM OFISIS.OFIPLAN.dbo.TDVACA AS V INNER JOIN
	OFISIS.OFIPLAN.dbo.TMTRAB_EMPR AS TE ON TE.CO_EMPR = V.CO_EMPR AND TE.CO_TRAB = V.CO_TRAB AND V.FE_INIC_VACA >= TE.FE_INGR_EMPR INNER JOIN
	OFISIS.OFIPLAN.dbo.TMTRAB_PERS AS TP ON TP.CO_TRAB = TE.CO_TRAB INNER JOIN
	OFISIS.OFIPLAN.dbo.TMEMPR AS E ON E.CO_EMPR = V.CO_EMPR INNER JOIN
	OFISIS.OFIPLAN.dbo.TTAYUD_FORM AS AY ON AY.CO_TIPO = V.TI_VACA
WHERE (V.TI_SITU = 'APR') AND (AY.CO_AYUD = 'VAC') AND (V.TI_VACA IN ('TRA', 'FIS', 'NRE'))